# Exported from Render on 2025-10-01T23:35:29Z
version: "1"
services:
  - type: web
    name: PAGINA WEB
    runtime: docker
    repo: https://github.com/juanclosada/web
    plan: free
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
